name: flutter_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/img/landscape1.jpg
  - assets/img/landscape2.JPG
  - assets/img/landscape3.jpg
  - assets/img/landscape4.JPG
  - assets/img/person1.png
  - assets/img/person2.png
  - assets/img/person3.png

